#!/usr/bin/env bash

#Bash script that displays all active IPv4 IPs on the machine it’s executed on.

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-

# displays all active IPv4 IPs on the machine it is executed on

ifconfig | grep -Po 'inet addr:\K\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
